### ISSUE TITLE
The cask named 'egovframedev' has been added to the Homebrew main repository

### ISSUE THREAD

**Issue by chris-yoon** [leejongyoung/homebrew-egovframe#1]
Dear leejongyoung,

I'm pleased to announce that the 'egovframedev' cask is now available in the Homebrew main repository.

For more information, please visit the eGovFrame's Homebrew Tap at the following link:

- eGovFrame's Homebrew Tap: https://github.com/eGovFramework/homebrew-egovframe

Thanks you for your attention.

Best regards,

eGovFrame Center

**Comment by leejongyoung** [comment]
Thank you for the update. I am genuinely interested in your solutions and appreciate the efforts you put into developing them. I will strive to contribute more to the eGovFrame that your organization manages in the future.
